myschool/myschool/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

# Views da aplicação utilizadores
from utilizadores import views as utilizadores_views


# View para testar a integração do Sentry


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    # Páginas Públicas
    path('', include('myschool_app.urls')),
    # Sentry
    path('sentry-debug/', trigger_error),
    # Páginas da Aplicação
    path('app/', include('myschool_app.urls_app')),
    # Administração
    path('admin/docs/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    # Autenticação
    path('app/registo/', utilizadores_views.registo, name='app-registar'),
    path('app/perfil/', utilizadores_views.perfil, name="app-perfil"),
    path('app/login/', auth_views.LoginView.as_view(
        template_name='utilizadores/login.html', redirect_authenticated_user=True), name='app-login'),
    path('app/logout/', auth_views.LogoutView.as_view(), name='app-logout'),
    # Recuperação da password
    path('app/recuperar-password/',
         auth_views.PasswordResetView.as_view(template_name="utilizadores/password/recuperar_password_form.html",
                                              email_template_name="utilizadores/password/recuperar_password_email.html"),
         name="recuperar-password"),
    path('app/recuperar-password/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="utilizadores/password/recuperar_password_alteracao.html"),
         name="password_reset_confirm"),
    path('app/recuperar-password/enviado/', auth_views.PasswordResetDoneView.as_view(
        template_name="utilizadores/password/recuperar_password_concluido.html"), name="password_reset_done"),
    path('app/recuperar-password/recuperada/', auth_views.PasswordResetCompleteView.as_view(
        template_name="utilizadores/password/recuperar_password_feito.html"),
         name="password_reset_complete")
]

# Se a opção DEBUG = True
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myschool/myschool_app/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    # Páginas Públicas
    path('', InicioView.as_view(), name="publico-inicio"),
    path('sobre/', SobreView.as_view(), name="publico-sobre"),
    path('equipa/', EquipaView.as_view(), name="publico-equipa"),
    path('funcionalidades/', FuncionalidadesViews.as_view(),
         name="publico-funcionalidades"),
    path('contactos/', ContactosView.as_view(), name="publico-contactos")
]

myschool/myschool_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


# Professor


class Professor(models.Model):
    utilizador = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name=_('Utilizador'))
    nome = models.CharField(max_length=50, verbose_name=_('Nome'))
    email = models.EmailField(verbose_name=_('Endereço de Email'), blank=True)
    telefone = models.CharField(
        max_length=20, verbose_name=_('Telefone'), blank=True)

    class Meta:
        verbose_name = _('Professor')
        verbose_name_plural = _('Professores')

    def __str__(self):
        return self.nome


# Disciplina


class Disciplina(models.Model):
    utilizador = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name=_('Utilizador'))
    descricao = models.CharField(max_length=50, verbose_name=_('Descrição'))
    professor = models.ForeignKey(
        'Professor', on_delete=models.SET_NULL, blank=True, null=True, verbose_name=_('Professor'))

    class Meta:
        verbose_name = _('Disciplina')
        verbose_name_plural = _('Disciplinas')

    def get_absolute_url(self):
        return reverse('app-disciplinas-editar', kwargs={'pk': self.pk})

    def __str__(self):
        return self.descricao


# Teste


class Teste(models.Model):
    utilizador = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name=_('Utilizador'))
    disciplina = models.ForeignKey(
        'Disciplina', on_delete=models.CASCADE, verbose_name=_('Disciplina'))
    data = models.DateField(verbose_name=_('Data'))
    notas = models.TextField(
        max_length=255, blank=True, verbose_name=_('Notas'))
    realizado = models.BooleanField(
        verbose_name=_('Realizado?'), blank=True, null=True)
    avaliacao = models.FloatField(
        verbose_name=_('Avaliação'), blank=True, null=True)

    class Meta:
        verbose_name = _('Teste')
        verbose_name_plural = _('Testes')

    def __str__(self):
        return self.disciplina.descricao


# Evento


class Evento(models.Model):
    utilizador = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name=_('Utilizador'))
    titulo = models.CharField(max_length=50, verbose_name=_('Título'))
    descricao = models.CharField(max_length=255, verbose_name=_('Descrição'))
    data_inicio = models.DateField(verbose_name=_('Data de Início'))
    data_fim = models.DateField(verbose_name=_('Data de Fim'))

    class Meta:
        verbose_name = _('Evento')
        verbose_name_plural = _('Eventos')

    def __str__(self):
        return self.titulo

myschool/myschool_app/forms.py
from django import forms
from myschool_app.models import *


# Disciplinas


class DisciplinaForm(forms.ModelForm):
    """
    Formulário para criação e edição de disciplinas
    """

    class Meta:
        model = Disciplina
        fields = ['descricao', 'professor', ]

    def __init__(self, *args, **kwargs):
        # utilizador que tem sessão iniciada na aplicação
        utilizador = kwargs.pop('user')
        super(DisciplinaForm, self).__init__(*args, **kwargs)
        # filtra os professores que pertencem ao utilizador acima
        self.fields['professor'].queryset = Professor.objects.filter(
            utilizador=utilizador)


# Testes


class TesteForm(forms.ModelForm):
    """
    Formulário para criação e edição de testes
    """

    class Meta:
        model = Teste
        fields = ['disciplina', 'data', 'notas']

    def __init__(self, *args, **kwargs):
        # utilizador que tem sessão iniciada na aplicação
        utilizador = kwargs.pop('user')
        super(TesteForm, self).__init__(*args, **kwargs)
        # filtra os professores que pertencem ao utilizador acima
        self.fields['disciplina'].queryset = Disciplina.objects.filter(
            utilizador=utilizador)


# Testes


class TesteAvaliacaoForm(forms.ModelForm):
    """
    Formulário para criação e edição de testes
    """

    class Meta:
        model = Teste
        fields = ['realizado', 'avaliacao', 'notas']

myschool/myschool_app/views.py
from django.views.generic import TemplateView


# Página Inicial


class InicioView(TemplateView):
    """
    Mostra a página inicial
    """
    template_name = 'myschool_app/publico/index.html'


# Funcionalidades


class FuncionalidadesViews(TemplateView):
    """
    Mostra a página funcionalidades
    """
    template_name = 'myschool_app/publico/funcionalidades.html'


# Sobre


class SobreView(TemplateView):
    """
    Mostra a página sobre
    """
    template_name = 'myschool_app/publico/sobre.html'


class EquipaView(TemplateView):
    """
    Mostra a página equipa
    """
    template_name = 'myschool_app/publico/equipa.html'


# Contactos


class ContactosView(TemplateView):
    """
    Mostra a página contactos
    """
    template_name = 'myschool_app/publico/contactos.html'

myschool/myschool_app/templates/myschool_app/app/disciplinas.html
{% extends 'myschool_app/app/base.html' %}
{% load i18n %}

{% block title %}
  {% trans 'Disciplinas' %}
{% endblock title %}

{% block content %}
  <h2><i class="fas fa-bookmark"></i> {% trans 'Disciplinas' %}</h2>

  <div class="row mt-4">
    <div class="col-md-10">
      <!-- Mensagens -->
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}
      {% endif %}

      <a href="{% url 'app-disciplinas-adicionar' %}" class="btn btn-sm btn-info mb-3"> <i
              class="fas fa-plus"></i> {% trans 'Adicionar' %}</a>

      {% if disciplinas %} <!-- Verifica se existem disciplinas registadas -->
        <table class="table table-hover">
          <thead class="thead-light">
          <tr>
            <th scope="col">{% trans 'Descrição' %}</th>
            <th scope="col">{% trans 'Professor' %}</th>
            <th scope="col">{% trans 'Opções' %}</th>
          </tr>
          </thead>
          <tbody>
          {% for disciplina in disciplinas %}
            <tr>
              <td>{{ disciplina.descricao }}</td>
              {% trans 'Sem Professor' as sem_professor %}
              <td>{{ disciplina.professor|default_if_none:sem_professor }}</td>
              <td>
                <a href="{% url 'app-disciplinas-editar' disciplina.id %}"
                   class="btn btn-warning btn-sm">{% trans 'Editar' %}</a>
                <a href="{% url 'app-disciplinas-remover' disciplina.id %}"
                   class="btn btn-danger btn-sm">{% trans 'Remover' %}</a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      {% else %}
        <div class="my-4">
          <h4>{% trans 'Não tem disciplinas registadas' %}</h4>
          <p>
            {% blocktrans %}Utilize a opção <span class="badge badge-info">Adicionar</span> para adicionar
              registos.{% endblocktrans %}
          </p>
        </div>
      {% endif %}
    </div>
    <!-- Dica -->
    <div class="col-md-2">
      <div class="card text-center">
        <div class="card-header text-white bg-dark">
          <i class="fas fa-2x fa-lightbulb m-2"></i> <br/>
          <h4>{% trans 'Dica' %}</h4>
        </div>
        <div class="card-body m-0 p-3">
          <p>
            {% trans 'Não precisas de registar professores para adicionares disciplinas.' %}
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

myschool/myschool_app/templates/myschool_app/app/disciplinas_form.html
{% extends 'myschool_app/app/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
  {% trans 'Disciplinas' %}
{% endblock title %}

{% block content %}
  <h2><i class="fas fa-bookmark"></i> {% trans 'Disciplinas' %}</h2>

  <div class="row mt-4">
    <div class="col">
      <form method="POST">
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-6">
            {{ form.descricao|as_crispy_field }}
          </div>
          <div class="form-group col-md-6">
            {{ form.professor|as_crispy_field }}
          </div>
        </div>
        <a href="{% url 'app-disciplinas-lista' %}" class="btn btn-dark">{% trans 'Voltar' %}</a>
        <input type="submit" class="btn btn-info" value="{% trans 'Guardar' %}">
      </form>
    </div>
  </div>
{% endblock content %}

myschool/myschool_app/templates/myschool_app/app/disciplinas_remover.html
{% extends 'myschool_app/app/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
  {% trans 'Remover Disciplina' %}
{% endblock title %}

{% block content %}
  <h2><i class="fas fa-bookmark"></i> {% trans 'Disciplinas' %}</h2>

  <div class="row mt-4">
    <div class="col">
      <form method="POST">
        {% csrf_token %}
        <p class="my-3">
          {% blocktrans with disciplina=disciplina.descricao %} Queres mesmo remover a disciplina
            <strong>{{ disciplina }}</strong>?{% endblocktrans %}
        </p>

        <a href="{% url 'app-disciplinas-lista' %}" class="mt-4 btn btn-dark">{% trans 'Voltar' %}</a>
        <input type="submit" class="mt-4 btn btn-danger" value="{% trans 'Remover' %}">
      </form>
    </div>
  </div>
{% endblock content %}

myschool/myschool_app/templates/myschool_app/app/eventos.html
{% extends 'myschool_app/app/base.html' %}
{% load i18n %}

{% block title %}
  {% trans 'Eventos' %}
{% endblock title %}

{% block content %}
  <h2><i class="fas fa-calendar-alt"></i> {% trans 'Eventos' %}</h2>

  <div class="row mt-4">
    <div class="col">
      <!-- Mensagens -->
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}
      {% endif %}

      <a href="{% url 'app-eventos-adicionar' %}" class="btn btn-sm btn-info mb-3"> <i
              class="fas fa-plus"></i> {% trans 'Adicionar' %}</a>

      {% if eventos %} <!-- Verifica se existem professores registadas -->
        <table class="table table-hover">
          <thead class="thead-light">
          <tr>
            <th scope="col">{% trans 'Título' %}</th>
            <th scope="col">{% trans 'Descrição' %}</th>
            <th scope="col">{% trans 'Data de Início' %}</th>
            <th scope="col">{% trans 'Data de Fim' %}</th>
            <th scope="col">{% trans 'Opções' %}</th>
          </tr>
          </thead>
          <tbody>
          {% for evento in eventos %}
            <tr>
              <td>{{ evento.titulo }}</td>
              <td>{{ evento.descricao }}</td>
              <td>{{ evento.data_inicio }}</td>
              <td>{{ evento.data_fim }}</td>
              <td>
                <a href="{% url 'app-eventos-editar' evento.id %}"
                   class="btn btn-warning btn-sm">{% trans 'Editar' %}</a>
                <a href="{% url 'app-eventos-remover' evento.id %}"
                   class="btn btn-danger btn-sm">{% trans 'Remover' %}</a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      {% else %}
        <div class="my-4">
          <h4>{% trans 'Não tem eventos registados' %}</h4>
          <p>
            {% blocktrans %}Utilize a opção <span class="badge badge-info">Adicionar</span> para adicionar
              registos.{% endblocktrans %}
          </p>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock content %}

myschool/myschool_app/templates/myschool_app/app/eventos_form.html
{% extends 'myschool_app/app/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
  {% trans 'Adicionar Evento' %}
{% endblock title %}

{% block content %}
  <h2><i class="fas fa-calendar-alt"></i> {% trans 'Eventos' %}</h2>

  <div class="row mt-4">
    <div class="col">
      <form method="POST">
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col">
            {{ form.titulo|as_crispy_field }}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            {{ form.data_inicio|as_crispy_field }}
          </div>
          <div class="form-group col-md-6">
            {{ form.data_fim|as_crispy_field }}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col">
            {{ form.descricao|as_crispy_field }}
          </div>
        </div>
        <a href="{% url 'app-eventos-lista' %}" class="btn btn-dark">{% trans 'Voltar' %}</a>
        <input type="submit" class="btn btn-info" value="{% trans 'Guardar' %}">
      </form>
    </div>
  </div>
{% endblock content %}

{% block scripts %}
  <script>
      $('#id_data_inicio').datepicker({
          format: 'yyyy-mm-dd',
          language: 'pt'
          //startDate: '0d'
      });
      $('#id_data_fim').datepicker({
          format: 'yyyy-mm-dd',
          language: 'pt'
          //startDate: '0d'
      });

      // Validação de datas
      $('form').submit(function () {
          var data_inicio = $('#id_data_inicio').val();
          var data_fim = $('#id_data_fim').val();

          if (data_fim < data_inicio) {
              toastr["error"]("A data de fim não pode ser anterior à data de início!", "Validação")
              return false;
          } else {
              return true;
          }
      });
  </script>
{% endblock scripts %}

myschool/myschool_app/templates/myschool_app/app/eventos_remover.html
{% extends 'myschool_app/app/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
  {% trans 'Remover Evento' %}
{% endblock title %}

{% block content %}
  <h2><i class="fas fa-calendar-alt"></i> {% trans 'Eventos' %}</h2>

  <div class="row mt-4">
    <div class="col">
      <form method="POST">
        {% csrf_token %}
        <p class="my-3">
          {% blocktrans with titulo=evento.titulo data=evento.data_inicio %}Queres mesmo remover o evento com o título
            <strong>{{ titulo }}</strong> do dia <strong>{{ data }}</strong>? {% endblocktrans %}
        </p>

        <a href="{% url 'app-eventos-lista' %}" class="mt-4 btn btn-dark">{% trans 'Voltar' %}</a>
        <input type="submit" class="mt-4 btn btn-danger" value="{% trans 'Remover' %}">
      </form>
    </div>
  </div>
{% endblock content %}

myschool/myschool_app/templates/myschool_app/app/index.html
{% extends 'myschool_app/app/base.html' %}
{% load i18n %}

{% block title %}
  {% trans 'Dashboard' %}
{% endblock title %}

{% block content %}
  <h2><i class="fas fa-tachometer-alt"></i> {% trans 'Dashboard' %}</h2>
  <h5 class="text-muted mb-4">{% trans 'Ponto de acesso para todas as informações' %}</h5>

  <div class="row mb-4">
    <div class="col-sm">
      <div class="d-flex border">
        <div class="bg-primary text-light p-4">
          <div class="d-flex align-items-center h-100">
            <i class="fa fa-3x fa-fw fa-book"></i>
          </div>
        </div>
        <div class="flex-grow-1 bg-white p-4">
          <p class="text-uppercase text-secondary mb-0">{% trans 'Disciplinas' %}</p>
          <h3 class="font-weight-bold mb-0">{{ quantidade_disciplinas }}</h3>
        </div>
      </div>
    </div>
    <div class="col-md">
      <div class="d-flex border">
        <div class="bg-success text-light p-4">
          <div class="d-flex align-items-center h-100">
            <i class="fa fa-3x fa-fw fa-comments"></i>
          </div>
        </div>
        <div class="flex-grow-1 bg-white p-4">
          <p class="text-uppercase text-secondary mb-0">{% trans 'Testes' %}</p>
          <h3 class="font-weight-bold mb-0">{{ quantidade_testes }}</h3>
        </div>
      </div>
    </div>
    <div class="col-md">
      <div class="d-flex border">
        <div class="bg-danger text-light p-4">
          <div class="d-flex align-items-center h-100">
            <i class="fa fa-3x fa-fw fa-users"></i>
          </div>
        </div>
        <div class="flex-grow-1 bg-white p-4">
          <p class="text-uppercase text-secondary mb-0">{% trans 'Professores' %}</p>
          <h3 class="font-weight-bold mb-0">{{ quantidade_professores }}</h3>
        </div>
      </div>
    </div>
    <div class="col-md">
      <div class="d-flex border">
        <div class="bg-info text-light p-4">
          <div class="d-flex align-items-center h-100">
            <i class="fa fa-3x fa-fw fa-calendar"></i>
          </div>
        </div>
        <div class="flex-grow-1 bg-white p-4">
          <p class="text-uppercase text-secondary mb-0">{% trans 'Eventos' %}</p>
          <h3 class="font-weight-bold mb-0">{{ quantidade_eventos }}</h3>
        </div>
      </div>
    </div>
  </div>

  <div class="row mb-4">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header bg-success text-white font-weight-bold"><i
                class="fas fa-forward"></i> {% trans 'Próximos Testes' %}</div>
        <div class="card-body">
          {% if testes %}
            <table class="table table-hover">
              <thead>
              <tr>
                <th scope="col">{% trans "Data" %}</th>
                <th scope="col">{% trans "Disciplina" %}</th>
                <th scope="col">{% trans "Estado" %}</th>
                <th scope="col">{% trans "Opções" %}</th>
              </tr>
              </thead>
              <tbody>
              {% for teste in testes %}
                <tr>
                  <td>{{ teste.data|date:'d/M/Y' }}</td>
                  <td>
                    <a href="{% url 'app-disciplinas-editar' teste.disciplina.id %}">
                      {{ teste.disciplina }}
                    </a>
                  </td>
                  <td>
                    {% if teste.avaliacao is None %}
                      <span class="badge badge-warning">
                          {% blocktrans %}Por Avaliar{% endblocktrans %}
                        </span>
                      <!-- @todo Implementar escala de avaliações -->
                    {% else %}
                      <span class="badge badge-dark">
                          {% blocktrans %}Avaliado: {{ teste.avaliacao }}{% endblocktrans %}
                        </span>
                    {% endif %}
                  </td>
                  <td>
                    <a href="{% url 'app-testes-editar' teste.id %}"
                       class="btn btn-info btn-sm">{% trans "Editar" %}</a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
            {% url 'app-testes-lista' as url %}
            <small class="text-muted">{% blocktrans %}Consulte todos os testes
              <a href="{{ url }}">aqui</a>.{% endblocktrans %}</small>
          {% else %}
            <h4>{% blocktrans %}Sem registos.{% endblocktrans %}</h4>
            <p>{% blocktrans %}<a href="{{ url }}">Adicione registos</a> para
              começar.{% endblocktrans %}</p>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card">
        <div class="card-header bg-info text-white font-weight-bold"><i
                class="fas fa-calendar"></i> {% trans "Próximos Eventos" %}</div>
        <div class="card-body">
          {% if eventos %}
            <table class="table table-hover">
              <thead>
              <tr>
                <th scope="col">{% blocktrans %}Data de Início{% endblocktrans %}</th>
                <th scope="col">{% trans "Título" %}</th>
              </tr>
              </thead>
              <tbody>
              {% for evento in eventos %}
                <tr>
                  <td>{{ evento.data_inicio|date:'d/M/Y' }}</td>
                  <td>
                    <a href="{% url 'app-eventos-editar' evento.id %}">{{ evento.titulo }}</a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          {% else %}
            {% url 'app-eventos-lista' as url %}
            <h4>{% blocktrans %}Sem registos.{% endblocktrans %}</h4>
            <p>{% blocktrans %}<a href="{{ url }}">Adicione registos</a> para
              começar.{% endblocktrans %}</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

myschool/myschool_app/templates/myschool_app/app/professores_form.html
{% extends 'myschool_app/app/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
  {% trans 'Professores' %}
{% endblock title %}

{% block content %}
  <h2><i class="fas fa-user-friends"></i> {% trans 'Professores' %}</h2>

  <div class="row mt-4">
    <div class="col">
      <form method="POST">
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-4">
            {{ form.nome|as_crispy_field }}
          </div>
          <div class="form-group col-md-4">
            {{ form.email|as_crispy_field }}
          </div>
          <div class="form-group col-md-4">
            {{ form.telefone|as_crispy_field }}
          </div>
        </div>
        <a href="{% url 'app-professores-lista' %}" class="btn btn-dark">{% trans 'Voltar' %}</a>
        <input type="submit" class="btn btn-info" value="{% trans 'Guardar' %}">
      </form>
    </div>
  </div>
{% endblock content %}

myschool/myschool_app/templates/myschool_app/app/testes_avaliacao_form.html
{% extends 'myschool_app/app/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
  {% trans 'Adicionar Avaliação' %}
{% endblock title %}

{% block content %}
  <h2><i class="fas fa-file-alt"></i> {% trans 'Testes' %}</h2>

  <div class="row mt-4">
    <div class="col">
      <form method="POST" id="form-avaliacao">
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-2">
            {{ form.avaliacao|as_crispy_field }}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col">
            {{ form.notas|as_crispy_field }}
          </div>
        </div>
        <a href="{% url 'app-testes-lista' %}" class="btn btn-dark">{% trans 'Voltar' %}</a>
        <input type="submit" class="btn btn-info" value="{% trans 'Guardar' %}">
      </form>
    </div>
  </div>
{% endblock content %}

{% block scripts %}
  <script>
      // Validação do campo Avaliação
      // Apenas pode conter valores entre 0 e 20
      $('#form-avaliacao').submit(function () {
          var avaliacao = $.trim($('#id_avaliacao').val());

          if (avaliacao > 20) {
              toastr.error('A nota de avaliação tem de estar entre 0 e 20!', 'Erro');
              return false;
          }
      });
  </script>
{% endblock scripts %}

myschool/myschool_app/templates/myschool_app/app/testes_form.html
{% extends 'myschool_app/app/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
  {% trans 'Testes' %}
{% endblock title %}

{% block content %}
  <h2><i class="fas fa-file-alt"></i> {% trans 'Testes' %}</h2>

  <div class="row mt-4">
    <div class="col">
      <form method="POST">
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-6">
            {{ form.disciplina|as_crispy_field }}
          </div>
          <div class="form-group col-md-6">
            {{ form.data|as_crispy_field }}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col">
            {{ form.notas|as_crispy_field }}
          </div>
        </div>

        <a href="{% url 'app-testes-lista' %}" class="btn btn-dark">{% trans 'Voltar' %}</a>
        <input type="submit" class="btn btn-info" value="{% trans 'Guardar' %}">
      </form>
    </div>
  </div>
{% endblock content %}

{% block scripts %}
  <script>
      $('#id_data').datepicker({
          format: 'dd/mm/yyyy',
          language: 'pt',
          startDate: '0d'
      });
  </script>
{% endblock scripts %}

myschool/myschool_app/templates/myschool_app/app/testes_graficos.html
{% extends 'myschool_app/app/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
  {% trans 'Testes' %}
{% endblock title %}

{% block content %}
  <h2><i class="fas fa-file-alt"></i> {% trans 'Testes' %}</h2>

  <div class="row mt-4">
    <div class="col">
      {{ line_chart.as_html }}
    </div>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.bundle.min.js"></script>
{% endblock content %}

{% block scripts %}

{% endblock scripts %}